# Generated by Django 6.0.3 on 2026-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_water_target_ml',
            field=models.PositiveIntegerField(default=750, help_text='Patients only: daily water intake target in millilitres.'),
        ),
    ]
