# Generated by Django 6.0.3 on 2026-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintakelog',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
