# Generated by Django 6.0.3 on 2026-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('finished', 'Selesai kursus'), ('symptoms', 'Efek samping'), ('out', 'Habis'), ('doctor', 'Dihentikan dokter'), ('other', 'Lainnya')], max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='stopped_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
